### ISSUE TITLE
leafleticon used in another element doesn't work

### ISSUE THREAD

**Issue by atdotslashdot** [nhnb/leaflet-map#16]
```html
<polymer-element name="my-thing" >
<template>
...
<leaflet-map latitude="51.505" longitude="-0.09" zoom="13">
<leaflet-icon id="myicon" 
    iconurl="https://stendhalgame.org/images/mapmarker/me.png"> </leaflet-icon>

<leaflet-marker latitude="51.5" longitude="-0.10" title="Element" icon="myicon">
```
I think the problem is at line 599 of leaflet-marker.html 
```html
var iconElement = document.getElementById(this.icon);
```
since the element will be in the shadow DOM, document.getElementById will fail.(return null)

**Comment by nhnb** [comment]
I cannot reproduce the issue. It works for me 
* in both Firefox and Chrome 
* on Polymer 0.5 and 0.9
* with dom=shady and dom=shadow

**Comment by manderson23** [comment]
The Polymer Starter Kit was using shadow DOM. When I changed to shady DOM it worked.
