### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by Granze** [nhnb/leaflet-map#19]
I just would like to know if you are interested to continue developing this project or not.

**Comment by nhnb** [comment]
It's not dead. There will be a new version when Polymer 0.8 gets more stable. At this point, I don't want to break compatibility just yet.

**Comment by Granze** [comment]
Nice to hear that. :)
Well Polymer 0.8 is stable, they marked the branch as RC because not all the elements are migrated yet.
I'm really interested to have an updated leaftlet-polymer component. I found your project and [this one](https://github.com/prtksxna/leaflet-map-component). Have you ever thought of collaborating with the author (and maybe merge the two projects)?
I'll interested in contributing at the project in that case.

Let me know, thanks

**Comment by nhnb** [comment]
Hello Granze,

please check out the 0.9 branch. As far as I can tell, everything seems to work now, but additional testing and feedback is very welcomed. I am struggling with the automatic api documentation &lt;iron-doc-viewer&gt; and &lt;iron-component-page&gt; seem to be pretty much work in progress.

Regarding prtksxna's implementation, we discussed cooperation some time ago. I granted him commit access here and merged his work.

**Comment by Granze** [comment]
Cool, I'll take a look!
