### ISSUE TITLE
ZindexOffset Broken

### ISSUE THREAD

**Issue by jshortall** [nhnb/leaflet-map#20]
In https://github.com/nhnb/leaflet-map/blob/master/leaflet-marker.html#L570

the zindexOffset key should be zIndexOffset (capital "I")

If you'd like a pull request I can put that together, but I thought one character might be easier just to edit on your own.

Thanks! Great element!

**Comment by nhnb** [comment]
Thank your for the bug fix. It is committed in the 0.9 branch.

Please note: The javascript property is still called zIndexOffset, but the attribute will be called z-index-offset to stay in sync with the naming convention of Polymer 0.9
